export { NameModificator } from './changeAPIresponseData/changeAPIresponseData';
export { setContent } from './setComponentContent/setContent';
export { createData } from './createTableCurrencyRatesData/createData';
export { isInRequiredRange } from './validateCustomTextInput/validateCustomTextInput';
export { createNewCurrencyStateObject } from './createNewCurrencyStateObject/createNewCurrencyStateObject';
export { changeInitialCurrencyRateState } from './changeInitialCurrencyRateState/changeInitialCurrencyRateState';
export { emulateServerError } from './emulateServerError/emulateServerError';
export { changeApiObject } from './changeAPIresponseData/changeAPIresponseData';
export { changeBtcAPIObject } from './changeBtcAPIObject/';
